name: Continuous Integration

on:
  push:
    branches:
      - main
      - desenvolvimento
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Verificar arquivos
        run: ls -la

      - name: Teste simples
        run: echo "CI funcionando com sucesso"