name: CI

on:
  push:
    branches: [ main, desenvolvimento ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Teste simples
        run: echo "Pipeline funcionando"