name: Testes Unitários

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependências
        run: composer install

      - name: Dar permissão ao PHPUnit
        run: chmod +x vendor/bin/phpunit

      - name: Rodar testes
        run: vendor/bin/phpunit tests